---
version: 0.2

env:
  shell: bash

phases:
  install:
    commands: |
      python --version
      node --version
      aws --version
  pre_build:
    commands: |
      echo "Login into ECR..."
      aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands: |
      echo "Building image..."
      docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands: |
      echo "Pushing the Docker image..."
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
